### ISSUE TITLE
some observations

### ISSUE THREAD

**Issue by xquery** [adamfowleruk/mlcplusplus#111]
Nice work, just forked and had a brief peek around ... hope you do not mind I have scratched out some random, quick observations (no need to respond).

I was also unable to build as your repo is missing bin directory (and maybe something else?) ... perhaps you missed off committing (or I need a clue) ?

While I think the MS style of distro is entirely fine (and a matter of taste/IDE pref) I personally find it harder to comprehend at first glance ... for example,  /release dir would be named /mlcplusplus and would follow through with same namespace ... though you have used  mlclient. Not a criticism just my personal grokking. 

To get inspired here is a pretty good curated list of c++ projects

   https://github.com/fffaraz/awesome-cpp

I try to segregate any third party into a thirdparty directory (ex. easylogging++)  or include directory if appropriate (I did not find any though CMakeLists.txt refers to a ../include). Doing this also keeps  licenses explicit (ex. easylogging++ has MIT license). 

Have you considered an option to build in casablanca (perhaps as a git submodule) ?

I find gtest to be the best of whats out there in terms of testing

   https://github.com/google/googletest

once again, a matter of taste.

The cmake vs autoconf debate continues to rage for me ... I think cmake is the where the world is inevitably headed so good to see it here. 

Getting a modern travis env can be a mite difficult

   http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/

helped me recently.

I am a C++ novice (though long time c programmer) so take my comments as you may - great to see this project taking shape ... once I can build will see if I can comment or contrib anything useful in my 'copious spare time'.

**Comment by adamfowleruk** [comment]
Hey! Thanks for the feedback - I need as much as I can get. I started following the MS route just for convenience, but not opposed to changing anything at this stage. I'm slowly moving dependencies in to other folders. 

I like the idea of embedding casablanca in the binary, given it's only available as source.

I'm renaming everything to mlclient as otherwise it would make developers #include <MLCPlusPlus/Connection.hpp> which is just nasty and bound to cause issues. Not gotten around to changing everything yet. Thinking of keeping the repo name the same just for clarity.

Good point about the bin directory - I'll update the clean and gen- scripts for this.

Keep the thoughts coming!

**Comment by adamfowleruk** [comment]
Built in most dependencies - not easy to do for casablanca, so left that as the one dependency. NuGet packages for windows means this is done for your.

Travis cannot build the dependencies quickly enough to finish in time, so I'm going to turn that off and rely on automated testing locally prior to completing a release.

Now using ext folders in my include and source folders - has saved a lot of headache!

I now also have set up scripts for *nix - run gen-eclipse.sh for example, and that'll set up your bin folder, on *nix install-dependencies.sh sorts out dependencies for you.

Closing this issue as as all suggestions done! Thanks!
